FROM node:10.16-alpine
RUN mkdir /app
WORKDIR /app
COPY package.json package-lock.json /app/
RUN npm install
# Copy all the files
COPY . /app/
RUN npm run build
EXPOSE 3000
# RUN START
CMD [ "npm", "start"]%   